default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mttrs_development

test:
  <<: *default
  database: mttrs_test

production:
  <<: *default
  database: mttrs_production
  username: mttrs
  password: <%= ENV['MTTRS_DATABASE_PASSWORD'] %>
