default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  reaping_frequency: 10
  timeout: 10000

development:
  <<: *default
  database: mttrs_development

test:
  <<: *default
  database: mttrs_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV['DB_POOL'] %>
  port: <%= ENV['DB_PORT'] %>
  reaping_frequency: <%= ENV['DB_REAPING_FREQUENCY'] %>
  timeout: <%= ENV['DB_TIMEOUT'] %>
  username: <%= ENV['DB_USERNAME'] %>
