:verbose: true
development:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - [buzzsumo_entry_process, 3]
  - [indexer, 10]
  - [refresh_story, 3]
  - [story_builder, 6]
  - amp_fetcher
  - buzzsumo_fetcher
  - default
  - link_full_fetch
  - link_image_uploader
  - link_set_category
  - link_set_tags
  - mailers
  - notification_deliver
  - title_replacements
  - update_story_accesses
:limits:
  # story_builder: 3
  buzzsumo_fetcher: 6
  link_full_fetch: 3
  update_story_accesses: 3
  link_image_uploader: 5
