:verbose: true
development:
  :concurrency: 10
production:
  :concurrency: 25
:queues:
  - [indexer, 15]
  - [story_builder, 10]
  - [default, 5]
  - [link_fetcher, 2]
  - [mailers, 1]
:limits:
  story_builder: 1
  link_fetcher: 2
