:verbose: true
development:
  :concurrency: 10
production:
  :concurrency: 35
:queues:
  - [default, 5]
  - [indexer, 15]
  - [link_fetcher, 2]
  - [link_full_fetch, 2]
  - link_categorizer
  - link_process
  - mailers
  - refresh_story
  - story_builder
  - story_merger
  - title_replacements
  - update_story_accesses
:limits:
  story_builder: 1
  link_fetcher: 2
  link_full_fetch: 2
