:verbose: true
development:
  :concurrency: 10
production:
  :concurrency: 25
:queues:
  - [indexer, 5]
  - [story_builder, 3]
  - [default, 2]
  - [mailers, 1]
  - [social_counter, 1]
:limits:
  story_builder: 1
