:verbose: true
development:
  :concurrency: 10
production:
  :concurrency: 30
:queues:
  - [indexer, 15]
  - [story_builder, 10]
  - [default, 5]
  - [mailers, 1]
  - [social_counter, 1]
:limits:
  story_builder: 1
