:verbose: true
development:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - [indexer, 10]
  - amp_fetcher
  - default
  - buzzsumo_fetcher
  - link_full_fetch
  - link_image_uploader
  - link_process
  - link_set_category
  - link_set_tags
  - mailers
  - notification_deliver
  - refresh_story
  - story_builder
  - title_replacements
  - update_story_accesses
:limits:
  # story_builder: 3
  buzzsumo_fetcher: 3
  link_full_fetch: 3
  update_story_accesses: 3
