:verbose: true
development:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - [indexer, 10]
  - amp_fetcher
  - default
  - link_fetcher
  - link_full_fetch
  - link_process
  - link_set_category
  - link_set_tags
  - mailers
  - notification_deliver
  - refresh_story
  - story_builder
  - title_replacements
  - update_story_accesses
:limits:
  story_builder: 1
  link_fetcher: 1
  link_full_fetch: 2
  update_story_accesses: 2
