:verbose: true
development:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - [indexer, 10]
  - default
  - link_categorizer
  - link_fetcher
  - link_full_fetch
  - link_process
  - mailers
  - refresh_story
  - story_builder
  - story_merger
  - title_replacements
  - update_story_accesses
:limits:
  story_builder: 1
  link_fetcher: 1
  link_full_fetch: 1
